[package]
name = "hecto"
version = "0.1.0"
edition = "2021"
authors = ["Junxi Wang wangjunxi@fake.com"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1"
